
name: tetris-stg-react


services:

  nginx-react:
    build:
      context: ../ # build context - it is project root inside Dockerfile
      dockerfile: ./deploy-docker/Dockerfile # path to Dockerfile relative to context
    image: tetris-stg-react-react
    ports:
      - '${PROXY_PORT}:${PROXY_PORT}'
    volumes:
      - ../deploy-nginx/nginx-react.nginx.conf:/etc/nginx/templates/nginx.conf.template:ro
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx # where to find 'templates/nginx.conf.template'
      - REACT_PORT
    restart: unless-stopped


  nginx-proxy:
    image: nginx:1.29.8-alpine
    network_mode: 'service:nginx-react'
    volumes:
      - ../deploy-nginx/nginx-proxy.nginx.conf:/etc/nginx/templates/nginx.conf.template:ro
      - ${PROXY_CERT_CRT}:/etc/ssl/cert/cert.crt:ro
      - ${PROXY_CERT_KEY}:/etc/ssl/cert/cert.key:ro
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx # where to find 'templates/nginx.conf.template'
      - PROXY_HOST
      - PROXY_PORT
      - PROXY_CERT_CRT
      - PROXY_CERT_KEY
      - REACT_PORT
    restart: unless-stopped



# nginx auto env substitution:
# https://stackoverflow.com/a/75183393/14168271
#
# nginx Docker image can extract environment variables before it starts, but it's a bit tricky.
# One solution is to:
#
# 1) Add env variables to your nginx.conf file.
# 2) Copy it to /etc/nginx/templates/nginx.conf.template in the container (as opposed to your normal /etc/nginx)
# in the build step or mount as a volume.
# 3) Set the NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx environment variable in docker-compose.yaml.
#
# This will cause the nginx.conf.template file to be copied to /etc/nginx as nginx.conf
# where environment variables will be replaced with their values.
#
# There is one caveat to keep in mind: using command property in docker-compose.yaml
# seems to be disabling the extraction functionality.
