/// <reference lib="webworker"/>
import { isobject } from '@@/utils/ts/ts.ts'
import type { WorkboxPlugin } from 'workbox-core'
import { ExpirationPlugin } from 'workbox-expiration'
import {
  precacheAndRoute,
  createHandlerBoundToURL,
  cleanupOutdatedCaches, matchPrecache, type PrecacheEntry,
} from 'workbox-precaching'
import { NavigationRoute, registerRoute } from 'workbox-routing'
import { envIsDev, envBaseUrl } from '@/app/env.ts'
import { CacheFirst } from 'workbox-strategies'
import { deployModeDefault } from '@/app-deploy/deployMode.model.ts'
import { getAppData } from '@/app-deploy/getAppData.ts'
import { deployLocaleDefault } from '@/app-deploy/locale/deployLocale.model.ts'
import { manifestToUpdated } from '@/app-deploy/manifest/manifestToUpdated.ts'
import { deployThemeDefault } from '@/app-deploy/theme/getAppDeployThemeData.ts'
import type { ManifestPart } from '@/app-deploy/manifest/manifest.model.ts'




// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

// Workbox strategies:
// https://developer.chrome.com/docs/workbox/modules/workbox-strategies




declare let self: ServiceWorkerGlobalScope




// Clear old precached entries
cleanupOutdatedCaches()

// self.__WB_MANIFEST contains precached entries that are assets generated by build process.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching.
const precacheManifest = self.__WB_MANIFEST
console.log('SW precacheManifest', precacheManifest)




{
  //const manifestPathPattern = new RegExp(`^${escapeForRegex(envBaseUrl)}manifest__[^/]*[.]json$`)
  const manifestPathPattern = new RegExp(`^manifest-[^/]*[.]json$`)
  //const manifestPathPattern = new RegExp(`^manifest[.]json$`)
  // @ts-expect-error
  const manifestPathData: PrecacheEntry | undefined = precacheManifest
    .find(it => isobject(it) && manifestPathPattern.test(it.url))
  if (manifestPathData) {
    let manifestPath = manifestPathData.url
    manifestPath = `${envBaseUrl}${manifestPath}`
    //console.log('manifest manifestPath', manifestPath)
    
    // Intercept & generate dynamic manifest
    registerRoute(
      ({ url }) => {
        //console.log('manifest url.pathname', url.pathname)
        return url.origin === self.location.origin && url.pathname === manifestPath
      },
      async ({ request, event, url, params }) => {
        // 'https://tetris.stg.rraindev:40200'
        //console.log('manifest origin', self.location.origin)
        // '/manifest-C6ydhvnX.json'
        console.log('manifest path', url.pathname)
        
        const cachedResponse = await matchPrecache(new URL(url.pathname, url.origin).toString())
        if (cachedResponse) {
          let manifest = await cachedResponse.json() as ManifestPart
          
          const deployMode = url.searchParams.get('deployMode') || deployModeDefault
          const deployLocale = url.searchParams.get('locale') || deployLocaleDefault
          const deployTheme = url.searchParams.get('theme') || deployThemeDefault
          
          const {
            appName, appDescription,
            themeColor, bgColor,
          } = getAppData({ deployMode, deployLocale, deployTheme })
          
          manifest = manifestToUpdated({
            manifest,
            locale: deployLocale,
            appName, appDescription,
            themeColor, bgColor,
          })
          
          return new Response(JSON.stringify(manifest, null, 2), {
            headers: { 'Content-Type': 'application/json' },
          })
        }
        
        return await fetch(request)
      }
    )
  }
}




// Precache all the assets generated by your build process.
// Precaching must be first route.
precacheAndRoute(precacheManifest)




if (!envIsDev) {
  // Set up App Shell-style routing, so that all navigation requests
  // are fulfilled with your index.html shell.
  // It allows processing route requests via index.html via react-router via SW.
  registerRoute(new NavigationRoute(createHandlerBoundToURL(`${envBaseUrl}index.html`)))
}




// Cache external (not project) data
registerRoute(
  ({ url }) => {
    /*
     console.log('url.pathname', url.pathname)
     console.log('url.pathname is image', extsPattern.test(url.pathname))
     console.log('url.origin', url.origin)
     console.log('self.location.origin', self.location.origin)
     console.log('url.origin === self.location.origin', url.origin === self.location.origin)
     */
    //if (url.origin !== self.location.origin) return false
    
    return url.origin !== self.location.origin
  },
  // You can use different cache strategies: new StaleWhileRevalidate(), new CacheFirst(), ...
  new CacheFirst({
    cacheName: 'externalData',
    plugins: [
      // You cannot set size limit for file or whole cache. It is opaque data.
      new ExpirationPlugin({
        // Automatically deletes the oldest entries beyond count limit.
        maxEntries: 300,
        // Automatically deletes files older than 30 days (in seconds)
        maxAgeSeconds: 30 * 24 * 60 * 60,
        // Tell the browser it can safely remove this cache when low disk space.
        // Automatically clears this cache if the browser runs out of space.
        purgeOnQuotaError: true,
      }),
    ] as WorkboxPlugin[],
  })
)




// Service Worker won't be stopped until the Promise passed to 'ev.waitUtil' is settled.
// ev.waitUntil((async () => { ... })()) - tells browser the work is going
// and that it shouldn't terminate SW until promise is settled.

// ev.ports[0]?.postMessage(<msg>) - send message back if sender has provided the port.

self.onmessage = ev => ev.waitUntil((async () => {
  //console.log('SW received:', ev.data)
  const { type, data } = ev.data ?? { }
  
  console.log('SW received:', ev.data)
  
  // Used by VitePWA to force 'waiting' SW become 'active' after click on reload button.
  // You can trigger skipWaiting via registration.waiting.postMessage({ type: 'SKIP_WAITING' }).
  if (type === 'SKIP_WAITING') {
    self.skipWaiting()
  }
  else if (type === 'CLEAR_CACHE') {
    await clearCache()
    ev.ports[0]?.postMessage({ type: 'CACHE_CLEARED' })
    //self.registration.unregister()
  }
  else if (type === 'CONSOLE_LOG') {
    console.log('service worker console.log', ev)
    ev.ports[0]?.postMessage({ type: 'OK', data: 'logged successfully' })
  }
})())




async function clearCache(): Promise<void> {
  const entryKeys = await caches.keys()
  await Promise.allSettled(entryKeys.map(key => caches.delete(key)))
}



/*
 Worker lifecycle:
 1) Installing.
    This is the first phase after registration.
    When the 'oninstall' handler completes, the service worker is considered 'installed'.
 2) Waiting.
    The service worker is waiting for ALL clients still using other service workers to be closed.
 3) Activating.
    Now there are no clients controlled by other service workers.
    When the 'onactive' handler completes, the service worker is considered 'activated'.
 4) Activated
    The service worker now controls the page.
 
 Uncontrolled client - client that does not have any service worker.
 Controlled client - client that already has any service worker.
 
 self.clients.claim() - Start control only uncontrolled clients.
 This does not trigger page reload.
 
 self.skipWaiting() - skips the 'waiting' phase and moves directly to activating.
 Forces controlled pages to update their service worker to this service worker.
 This reloads page.
 */

self.addEventListener('install', ev => ev.waitUntil((async () => {
  if (envIsDev) ev.waitUntil(self.skipWaiting())
})()))
self.addEventListener('activate', ev => ev.waitUntil((async () => {
  await self.clients.claim()
})()))
