/// <reference lib="webworker"/>
import { generateManifest } from '@/app-meta/generateManifest.ts'
import { getAppMetaOrDefault } from '@/app-meta/getAppMeta.ts'
import type { WorkboxPlugin } from 'workbox-core'
import { ExpirationPlugin } from 'workbox-expiration'
import {
  precacheAndRoute,
  createHandlerBoundToURL,
  precache,
  addRoute,
  cleanupOutdatedCaches,
} from 'workbox-precaching'
import { NavigationRoute, registerRoute } from 'workbox-routing'
import { CacheFirst, StaleWhileRevalidate } from 'workbox-strategies'
import { envIsDev, envBaseUrl } from '@/app/env.ts'





// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

// Workbox strategies:
// https://developer.chrome.com/docs/workbox/modules/workbox-strategies




declare let self: ServiceWorkerGlobalScope




// Clear old precached entries
cleanupOutdatedCaches()

// self.__WB_MANIFEST contains precached entries that are assets generated by build process.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching.
const selfWorkboxManifest = self.__WB_MANIFEST

console.log('SW precached (selfWorkboxManifest):', selfWorkboxManifest)

// Precache all the assets generated by your build process.
// Precaching must be first route.
precacheAndRoute(selfWorkboxManifest)




// any query+hash (all content after first '?' (greedy match mode))
//const anyQueryAndHash = /\?.*/
// path that has any file extension in the last path segment
//const anyFileExt = /\/[^\/?]*\.[^\/?]+/




if (!envIsDev) {
  // Set up App Shell-style routing, so that all navigation requests
  // are fulfilled with your index.html shell.
  // It allows processing route requests via index.html via react-router via SW.
  registerRoute(new NavigationRoute(createHandlerBoundToURL(`${envBaseUrl}index.html`)))
}




// Intercept manifest.json to cache & generate dynamic manifest
{
  const manifestStrategy = new StaleWhileRevalidate({
    cacheName: 'manifest',
    plugins: [new ExpirationPlugin({ maxEntries: 130 })] as WorkboxPlugin[],
  })
  
  registerRoute(
    ({ url }) => url.pathname === `${envBaseUrl}manifest.json`,
    async ({ request, event, url, params }) => {
      const { searchParams } = url
      const response = await manifestStrategy.handle({ request, event })
      let manifest = await response.json() as Record<string, any>
      
      //console.log('manifest', manifest)
      
      const buildMode = searchParams.get('buildMode') ?? ''
      const lang = searchParams.get('lang') ?? ''
      const { appLang, appName, appDescription } = getAppMetaOrDefault(buildMode, lang)
      manifest = generateManifest(buildMode, appLang, appName, appDescription)
      
      return new Response(JSON.stringify(manifest), {
        // Save original headers
        headers: response.headers,
      })
    }
  )
}




// TODO Limit by item size or store assets only from this project (with same origin)
// Dynamic assets cache (images, short clips, fonts)
{
  const imgExts = ['webp', 'svg', 'heic', 'heif', 'jpeg', 'jpg', 'png', 'bmp']
  const shortClips = ['gif', 'weba', 'apng', 'avif']
  const fontExts = ['ttf', 'woff', 'woff2', 'eot']
  const exts = [...imgExts, ...fontExts, ...shortClips]
  const extsPattern = new RegExp(`[.](${exts.join('|')})$`, 'i')
  
  registerRoute(
    // Add any other file extensions or routing criteria as needed.
    ({ url }) => {
      /*
      console.log('url.pathname', url.pathname)
      console.log('url.pathname is image', extsPattern.test(url.pathname))
      console.log('url.origin', url.origin)
      console.log('self.location.origin', self.location.origin)
      console.log('url.origin === self.location.origin', url.origin === self.location.origin)
       */
      //if (url.origin !== self.location.origin) return false
      
      if (envIsDev) return false
      
      return extsPattern.test(url.pathname)
    },
    // You can use different cache strategies: new StaleWhileRevalidate(), new CacheFirst(), ...
    new CacheFirst({
      cacheName: 'dynamicAssets',
      plugins: [new ExpirationPlugin({ maxEntries: 300 })] as WorkboxPlugin[],
    })
  )
}




// Service Worker won't be stopped until the Promise passed to 'ev.waitUtil' is settled.
// ev.waitUntil((async () => { ... })()) - tells browser the work is going
// and that it shouldn't terminate SW until promise is settled.

// ev.ports[0]?.postMessage(<msg>) - send message back if sender has provided the port.

self.onmessage = ev => ev.waitUntil((async () => {
  //console.log('SW received:', ev.data)
  const { type, data } = ev.data ?? { }
  
  console.log('SW received:', ev.data)
  
  // Used by VitePWA to force 'waiting' SW become 'active' after click on reload button.
  // You can trigger skipWaiting via registration.waiting.postMessage({ type: 'SKIP_WAITING' }).
  if (type === 'SKIP_WAITING') {
    self.skipWaiting()
  }
  else if (type === 'CLEAR_CACHE') {
    await clearCache()
    ev.ports[0]?.postMessage({ type: 'CACHE_CLEARED' })
    //self.registration.unregister()
  }
  else if (type === 'CONSOLE_LOG') {
    console.log('service worker console.log', ev)
    ev.ports[0]?.postMessage({ type: 'OK', data: 'logged successfully' })
  }
})())




async function clearCache(): Promise<void> {
  const entryKeys = await caches.keys()
  await Promise.allSettled(entryKeys.map(key => caches.delete(key)))
}



/*
 Worker lifecycle:
 1) Installing.
    This is the first phase after registration.
    When the 'oninstall' handler completes, the service worker is considered 'installed'.
 2) Waiting.
    The service worker is waiting for ALL clients still using other service workers to be closed.
 3) Activating.
    Now there are no clients controlled by other service workers.
    When the 'onactive' handler completes, the service worker is considered 'activated'.
 4) Activated
    The service worker now controls the page.
 
 Uncontrolled client - client that does not have any service worker.
 Controlled client - client that already has any service worker.
 
 self.clients.claim() - Start control only uncontrolled clients.
 This does not trigger page reload.
 
 self.skipWaiting() - skips the 'waiting' phase and moves directly to activating.
 Forces controlled pages to update their service worker to this service worker.
 This reloads page.
 */

self.addEventListener('install', ev => ev.waitUntil((async () => {
  if (envIsDev) ev.waitUntil(self.skipWaiting())
})()))
self.addEventListener('activate', ev => ev.waitUntil((async () => {
  await self.clients.claim()
})()))
